### ISSUE TITLE
When I was training the model, a problem occurred

### ISSUE THREAD

**Issue by chenjiachengzzz** [reach2sbera/ldct_nonlocal#3]
Training model from scrath
/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448272031/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "train_model.py", line 127, in <module>
    loss.backward()
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 256, 3, 3]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by reach2sbera** [comment]
did you modify any part of the code?

**Comment by chenjiachengzzz** [comment]
> did you modify any part of the code?

no, I just download your code and run

**Comment by reach2sbera** [comment]
set this flag "torch.autograd.set_detect_anomaly(True)", and see where the error is happening.

**Comment by chenjiachengzzz** [comment]
> set this flag "torch.autograd.set_detect_anomaly(True)", and see where the error is happening.

(env1) install@install-server:~/cjc/code/ldct_nonlocal-main$ CUDA_VISIBLE_DEVICES=2 python train_model.py 
Training model from scrath
/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448272031/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
[W python_anomaly_mode.cpp:104] Warning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "train_model.py", line 114, in <module>
    pred_pos_neg = netD(pos_neg_imgs)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/install/cjc/code/ldct_nonlocal-main/networks.py", line 218, in forward
    x = self.discriminator_net(input)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/install/cjc/code/ldct_nonlocal-main/networks.py", line 159, in forward
    x = self.conv2d(input)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1060, in _call_impl
    result = hook(self, input)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/utils/spectral_norm.py", line 105, in __call__
    setattr(module, self.name, self.compute_weight(module, do_power_iteration=module.training))
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/nn/utils/spectral_norm.py", line 92, in compute_weight
    weight = weight / sigma
 (function _print_stack)
Traceback (most recent call last):
  File "train_model.py", line 127, in <module>
    loss.backward()
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/install/.conda/envs/env1/lib/python3.6/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 256, 3, 3]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Sorry, I can't fix that.

**Comment by reach2sbera** [comment]
I guess this is due to the wrong version of PyTorch.

**Comment by chenjiachengzzz** [comment]
> I guess this is due to the wrong version of PyTorch.

can you tell me you version of torch

**Comment by reach2sbera** [comment]
1.4.0
